-- emlak.revy_data definition

CREATE TABLE `ilan_veri` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ilan_link` text DEFAULT NULL,
  `ilan_no` text DEFAULT NULL,
  `islem_tipi` text DEFAULT NULL,
  `mulk_turu` text DEFAULT NULL,
  `fiyat` text DEFAULT NULL,
  `oda_sayisi` text DEFAULT NULL,
  `metre_karesi` text DEFAULT NULL,
  `bulundugu_kat` text DEFAULT NULL,
  `ilan_durumu` text DEFAULT NULL,
  `il` text DEFAULT NULL,
  `ilce` text DEFAULT NULL,
  `semt` text DEFAULT NULL,
  `mahalle` text DEFAULT NULL,
  `ilan_basligi` text DEFAULT NULL,
  `ilan_tarihi` text DEFAULT NULL,
  `emlak_turu` text DEFAULT NULL,
  `ilan_sahibi` text DEFAULT NULL,
  `ofis` text DEFAULT NULL,
  `cep_tel` text DEFAULT NULL,
  `ilan_sahipligi` text DEFAULT NULL,
  `ilan_kaynagi` text DEFAULT NULL,
  `portal_ilan_no` text DEFAULT NULL,
  `ilan_aciklamasi` text DEFAULT NULL,
  `site_icerisinde` text DEFAULT NULL,
  `site_adi` text DEFAULT NULL,
  `esyali` text DEFAULT NULL,
  `net_metrekaresi` text DEFAULT NULL,
  `bulundugu_kati` text DEFAULT NULL,
  `kat_sayisi` text DEFAULT NULL,
  `isitma` text DEFAULT NULL,
  `bina_yasi` text DEFAULT NULL,
  `balkon` text DEFAULT NULL,
  `banyo_sayisi` text DEFAULT NULL,
  `aidat` text DEFAULT NULL,
  `kullanim_durumu` text DEFAULT NULL,
  `imar_durumu` text DEFAULT NULL,
  `aylik_kira_getirisi` text DEFAULT NULL,
  `krediye_uygunluk` text DEFAULT NULL,
  `takas` text DEFAULT NULL,
  `orjinal_link` text DEFAULT NULL,
  `meta` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`meta`)),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
